### ISSUE TITLE
animate sideNav

### ISSUE THREAD

**Issue by tommysullivan** [heartpoints/heartpoints.org#62]
https://material-ui.com/demos/drawers/#persistent-drawer

most of the code is already there, just missing a thing or two.

**Comment by aashreya** [comment]
Let me give this a try.

**Comment by tommysullivan** [comment]
Ash hey yeah! The code is almost there I think...

The link has a working example; I want the side nav to animate out and also to push the content over a bit when it does (instead of covering the content like it does today)

When i broke the example into separate files for tsx I broke something in the style code so hope it’s easy.

**Comment by aashreya** [comment]
Yeah I see most of the code, I had to move around the styles to make the top navigation bar and content move when clicked. It is a little bit of more work than what I though. Will have a PR in a day I hope.

**Comment by aashreya** [comment]
How do we link the issue to a PR ?

**Comment by aashreya** [comment]
Merged with #80
