### ISSUE TITLE
handle fb login failure more gracefully (currently blanks out page)

### ISSUE THREAD

**Issue by tommysullivan** [heartpoints/heartpoints.org#63]

**Comment by PatrickMetsch** [comment]
I took the following steps in an attempt to duplicate the issue, but cannot.

1) Create and assign a gibberish cookie value in the Cookies.set() call
2) Create a new Facebook profile and log in using it (warns that i'm not a developer)
3) Delete that Facebook account and try logging with its credentials. The FB account deletion process requires 30 days, and you cannot try to log in with the account without Facebook trying to get you to reactivate it. This process is all done within the Facebook React pop up, and enough clicking through eventually takes you to the Facebook login page. @tommysullivan

**Comment by tommysullivan** [comment]
Hey @PatrickMetsch if you remember, we reproduced this same problem ahead of time so you could jump right into the work:

1. Ensure the site is operating normally, by logging out of facebook, and then either (a) using a new incognito window or (b) using dev tools to clear the cookie completely (don't put a gibberish value)

2. With that done, go to the /dev url, and click login

3. When the facebook login window comes up, just click close button on the popup, without logging into facebook. You will see the error and a blank screen. 

--

Basically we can see from the error in the console in dev tools, if you examine the stack trace to understand where the error occurred, that we have been assuming in our onFacebookLoginComplete callback in the index.tsx file that there is a legit session, even though there are cases when the callback runs and there is not a legit session. So we basically need to understand what those cases are and then handle them. 

The solution for now can just be to act as though facebook login was never clicked unless we have a definite facebook session. There is no need to invent anything fancy or a new screen or anything like that. All we want to achieve is that at least the screen doesn't go blank.

Hope that helps!
